language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
stages:
  - name: test
    before_script: echo "TEST"
    script: npm test
  - name: build
    before_script: echo "BUILD"
    script: npm run build
on:
  branch: master
